parameters:
    grimkirill.queue.connection.driver.array: Queue\QueueBundle\Driver\ArrayDriver
    grimkirill.queue.connection.driver.stomp: Queue\QueueBundle\Driver\StompDriver
    grimkirill.queue.connection.driver.stomp_apollo: Queue\QueueBundle\Driver\StompApolloDriver
    grimkirill.queue.connection.driver.ampq: Queue\QueueBundle\Driver\AmpqDriver
    grimkirill.queue.connection.driver.direct: Queue\QueueBundle\Driver\DirectDriver

    grimkirill.queue.producer.class: Queue\QueueBundle\Model\Producer
    grimkirill.queue.consumer.class: Queue\QueueBundle\Model\Consumer
    grimkirill.queue.producer_config.class: Queue\QueueBundle\Model\Config
    grimkirill.queue.consumer_config.class: Queue\QueueBundle\Model\Config

services:
    grimkirill.queue.serializer.json:
        class: Queue\QueueBundle\Serializer\Json
    grimkirill.queue.serializer.string:
        class: Queue\QueueBundle\Serializer\String
    grimkirill.queue.serializer.serialize:
        class: Queue\QueueBundle\Serializer\Serialize

    grimkirill.queue.holder:
        class: Queue\QueueBundle\Model\QueueHolder

    grimkirill.queue.template.connection.stomp:
        class: %grimkirill.queue.connection.driver.stomp%

    grimkirill.queue.template.connection.stomp_apollo:
        class: %grimkirill.queue.connection.driver.stomp_apollo%

    grimkirill.queue.template.connection.array:
        class: %grimkirill.queue.connection.driver.array%

    grimkirill.queue.template.connection.direct:
        class: %grimkirill.queue.connection.driver.direct%
        calls:
            - [setContainer, [@service_container]]

    grimkirill.queue.template.connection.ampq:
        class: %grimkirill.queue.connection.driver.ampq%
